# theme: minima
# remote_theme: b2a3e8/jekyll-theme-console
# theme: jekyll-shell-theme
# remote_theme: tareqdandachi/jekyll-shell-theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-spaceship



